public class FakeBookingRepo {
    public void save(String id, BookingRequest req, Money monthly, Money deposit) {
        // In a real repo the ID would be generated by the store; we accept whatever
        // is passed but ensure callers can use UUIDs or other schemes.
        System.out.println("Saved booking: " + id);
    }
}
